language: go
go:
  - 1.5
  - 1.6
script:
  - curl -s https://raw.githubusercontent.com/pote/gpm/v1.3.2/bin/gpm > gpm
  - chmod +x gpm
  - ./gpm install
  - ./test.sh
notifications:
  email: false
sudo: false

